### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by Wolf727** [onlyphantom/blockchain#5]
npm start

> blockchain-docs@0.0.1 start /home/user1/blockchain
> gatsby develop

╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Gatsby collects anonymous usage analytics                            ║
║   to help improve Gatsby for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
║   To learn more, checkout https://gatsby.dev/telemetry                 ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'graphql/polyfills/objectValues'
Require stack:
- /home/user1/blockchain/node_modules/graphql-compose/lib/utils/schemaPrinter.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/ScalarTypeComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeHelpers.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/ListComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/UnionTypeComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/InterfaceTypeComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeByPath.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/InputTypeComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/ObjectTypeComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/TypeMapper.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/SchemaComposer.js
- /home/user1/blockchain/node_modules/graphql-compose/lib/index.js
- /home/user1/blockchain/node_modules/gatsby/dist/schema/types/derived-types.js
- /home/user1/blockchain/node_modules/gatsby/dist/schema/types/sort.js
- /home/user1/blockchain/node_modules/gatsby/dist/schema/types/node-interface.js
- /home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/inference-metadata.js
- /home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/index.js
- /home/user1/blockchain/node_modules/gatsby/dist/redux/index.js
- /home/user1/blockchain/node_modules/gatsby/dist/utils/get-static-dir.js
- /home/user1/blockchain/node_modules/gatsby/dist/commands/develop-process.js
- /home/user1/blockchain/.cache/tmp-21433-5BcR7Cc6Ea5B
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/user1/blockchain/node_modules/graphql-compose/lib/utils/schemaPrinter.js:32:44)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user1/blockchain/node_modules/graphql-compose/lib/utils/schemaPrinter.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/ScalarTypeComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeHelpers.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/ListComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/UnionTypeComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/InterfaceTypeComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeByPath.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/InputTypeComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/ObjectTypeComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/TypeMapper.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/SchemaComposer.js',
    '/home/user1/blockchain/node_modules/graphql-compose/lib/index.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/schema/types/derived-types.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/schema/types/sort.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/schema/types/node-interface.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/inference-metadata.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/index.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/redux/index.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/utils/get-static-dir.js',
    '/home/user1/blockchain/node_modules/gatsby/dist/commands/develop-process.js',
    '/home/user1/blockchain/.cache/tmp-21433-5BcR7Cc6Ea5B'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockchain-docs@0.0.1 start: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockchain-docs@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user1/.npm/_logs/2022-01-20T22_41_25_899Z-debug.log

**Comment by onlyphantom** [comment]
Can you clear cache (gatsby clean or delete the folder manually) and try again?

This is also handled by “yarn develop” in the script -> it clear the cache before attempting to run the app.


On 21 Jan 2022, at 06:43, Wolf727 ***@***.***> wrote:

﻿

npm start

***@***.*** start /home/user1/blockchain
gatsby develop

╔════════════════════════════════════════════════════════════════════════╗
║ ║
║ Gatsby collects anonymous usage analytics ║
║ to help improve Gatsby for all users. ║
║ ║
║ If you'd like to opt-out, you can use gatsby telemetry --disable ║
║ To learn more, checkout https://gatsby.dev/telemetry ║
║ ║
╚════════════════════════════════════════════════════════════════════════╝
internal/modules/cjs/loader.js:905
throw err;
^

Error: Cannot find module 'graphql/polyfills/objectValues'
Require stack:

  *   /home/user1/blockchain/node_modules/graphql-compose/lib/utils/schemaPrinter.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/ScalarTypeComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeHelpers.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/ListComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/UnionTypeComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/InterfaceTypeComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeByPath.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/InputTypeComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/ObjectTypeComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/TypeMapper.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/SchemaComposer.js
  *   /home/user1/blockchain/node_modules/graphql-compose/lib/index.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/schema/types/derived-types.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/schema/types/sort.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/schema/types/node-interface.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/inference-metadata.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/index.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/redux/index.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/utils/get-static-dir.js
  *   /home/user1/blockchain/node_modules/gatsby/dist/commands/develop-process.js
  *   /home/user1/blockchain/.cache/tmp-21433-5BcR7Cc6Ea5B
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:93:18)
at Object. (/home/user1/blockchain/node_modules/graphql-compose/lib/utils/schemaPrinter.js:32:44)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/user1/blockchain/node_modules/graphql-compose/lib/utils/schemaPrinter.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/ScalarTypeComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeHelpers.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/ListComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/UnionTypeComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/InterfaceTypeComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/utils/typeByPath.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/InputTypeComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/ObjectTypeComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/TypeMapper.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/SchemaComposer.js',
'/home/user1/blockchain/node_modules/graphql-compose/lib/index.js',
'/home/user1/blockchain/node_modules/gatsby/dist/schema/types/derived-types.js',
'/home/user1/blockchain/node_modules/gatsby/dist/schema/types/sort.js',
'/home/user1/blockchain/node_modules/gatsby/dist/schema/types/node-interface.js',
'/home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/inference-metadata.js',
'/home/user1/blockchain/node_modules/gatsby/dist/redux/reducers/index.js',
'/home/user1/blockchain/node_modules/gatsby/dist/redux/index.js',
'/home/user1/blockchain/node_modules/gatsby/dist/utils/get-static-dir.js',
'/home/user1/blockchain/node_modules/gatsby/dist/commands/develop-process.js',
'/home/user1/blockchain/.cache/tmp-21433-5BcR7Cc6Ea5B'
]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@***.*** start: gatsby develop
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ***@***.*** start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/user1/.npm/_logs/2022-01-20T22_41_25_899Z-debug.log

**Comment by Wolf727** [comment]
> Can you clear cache (gatsby clean or delete the folder manually) and try again? This is also handled by “yarn develop” in the script -> it clear the cache before attempting to run the app. 

npm cache?

**Comment by onlyphantom** [comment]
Gatsby cache.

https://www.gatsbyjs.com/docs/build-caching/

On 21 Jan 2022, at 08:56, Wolf727 ***@***.***> wrote:

﻿

Can you clear cache (gatsby clean or delete the folder manually) and try again? This is also handled by “yarn develop” in the script -> it clear the cache before attempting to run the app.

npm cache?
